version: '3'

services:
  postgres-notedb:
    image: "postgres:latest"
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin123
      POSTGRES_DB: notedb
    ports:
      - "5432:5432"
